In [1]:
#untuk memulai numpy perlu mengimport nya
#np singkatan dari numpy

#=======MENDAPATKAN ARRAY=========
import numpy as np

In [9]:
arr = np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8] #mendapatkan nilai array dari index ke 8 

8

In [4]:
arr[0:5] #mendapatkan nilai array dari 0 sampai 5

array([0, 1, 2, 3, 4])

In [ ]:
#=====MERUBAH DATA ARRAY==========

In [5]:
arr[0] = 9 #merubah nilai index 0 menjadi 9

In [6]:
arr

array([ 9,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[0:5] = 9 #merubah nilai index 0 sampai 5 menjadi 9

In [8]:
arr

array([ 9,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10])

In [10]:
data = arr[0:5] #kita tampung data array pada variabel baru yaitu data
data            #menampung data array dari index 0 sampai 4

array([9, 9, 9, 9, 9])

In [12]:
data[:] = 99  #ini merubah data array di variabel data 
data

array([99, 99, 99, 99, 99])

In [13]:
arr #menampilkan data sebenarnya

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [14]:
new = arr.copy() #data tersebut akan merubah data aslinya
new              #jika kita ingin menduplikasi data aslinya kita dapat menggunakan copy()

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [16]:
#===========ARRAY 2 DIMENSI==========

In [17]:
#array 2 dimensi(([isi pertama],[isi kedua]))
arr_2d = np.array(([4,23,66],[32,45,56]))
arr_2d

array([[ 4, 23, 66],
       [32, 45, 56]])

In [18]:
arr_2d[1] #menampilkan array 1 dimensi

array([32, 45, 56])

In [19]:
arr_2d[1][0] #menampilkan index 0 dari array ke-1

32

In [20]:
arr_2d[1,0] #cara numnpy menampilkan array 2d bisa menggunakan koma

32

In [21]:
arr_2d[0:2, 1:3] #menampilkan array bedasarkan rangenya dimana:
                 #0:2 adalah menampilkan index 0 sampai index 2
                 #1:3 adalah menampilkan index 1 sampai index 3

array([[23, 66],
       [45, 56]])

In [22]:
arr_2d[:2, 1:] #:2 dapat diartikan menampilkan index awal sampai index 2 dari array ke-1
               #1: dapat diartikan menampilkan index 1 sampai akhir dari array ke-2

array([[23, 66],
       [45, 56]])

In [23]:
#seleksi array
nilai = np.arange(1,11)
nilai

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
nilai > 5 #memberikan kondisi pada array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [25]:
nilai[nilai > 5] #menampilkan nilai array berdasarkan kondisinya

array([ 6,  7,  8,  9, 10])

In [26]:
#perhitungan data array
nilai + nilai

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
nilai * nilai

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [28]:
nilai - nilai

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
nilai / nilai

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])