In [15]:
#jawaban no 1
import numpy as np
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#jawaban no 2
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [17]:
#jawaban no 3 
aku = np.array(([0,1,2],[3,4,5],[6,7,8]))
aku

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
#jawaban no 4
np.random.rand(25)

array([0.48598663, 0.1817048 , 0.86277746, 0.59687186, 0.27365462,
       0.41134456, 0.75072816, 0.89362738, 0.70721012, 0.0310401 ,
       0.28647093, 0.83660702, 0.98617397, 0.24668239, 0.10497839,
       0.75645913, 0.79815425, 0.90783817, 0.35177441, 0.02303095,
       0.10548423, 0.86394903, 0.0032728 , 0.3548135 , 0.39090225])

In [21]:
#jawaban no 5
ahmad = np.arange(25)
ahmad.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
#jawaban no 6
ahmad = np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]))
ahmad [2:5, 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [34]:
#jawaban no 7
ahmad = np.arange(25)
ahmad[20]

20

In [37]:
#jawaban no 9
ahmad = np.arange(25)
ahmad.max()

24

In [38]:
ahmad.min()

0

In [39]:
ahmad.argmax()

24

In [40]:
ahmad.argmin()

0

In [42]:
#jawaban no 10
ahmad = np.arange(25)
ahmad[11:21]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])